#设置端口号，访问地址
server:
  port: 8888
  servlet:
    context-path: /house
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #设置日期格式
    jackson:
      date-format: yyyy-MM-dd
  #允许重启，自动刷新
  devtools:
    remote:
      restart:
        enabled: true
  resources:
    static-locations: classpath:/templates/,classpath:/static/

#配置mybatis
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.house.entity